### PR TITLE
Petclinic. Empty response tests

### PR DESCRIPTION
**Pull request by hurelhuyag**

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@jakzal Do you mind taking a look at this? For some reason all tests that request from empty query/views have a problem. I think it is a setup problem but not sure. Thanks!

**Comment by hurelhuyag** [comment]
I believe it is related to `symbio`, `lattice` module or somewhere nearby this 2 modules. And this bug is appeared recently.

**Comment by VaughnVernon** [comment]
It might be related to the single-node cluster or the fact that previous projects had some components started on the grid that should have been local only.

**Comment by jakzal** [comment]
Fix in symbio: https://github.com/vlingo/vlingo-symbio/compare/08782983347e...9b35cef1855d

**Pull request closed without merging**
