### PR TITLE
PetData support null visit property

### PR DESCRIPTION
**Pull request by hurelhuyag**

### CODE REVIEW

**Comment by VaughnVernon** [comment]
@hurelhuyag Is this a [WIP], or do you plan to merge it yourself, or do you want me to merge?

**Comment by hurelhuyag** [comment]
@VaughnVernon This is simple fix for `NullPointerException`. I need you to review this.

**Comment by VaughnVernon** [comment]
> @VaughnVernon This is simple fix for `NullPointerException`. I need you to review this.

Sorry, I don't see full test implementations. Did you forget to push some commits?

**Comment by hurelhuyag** [comment]
@VaughnVernon  I need time to understand how to write tests.

**Comment by hurelhuyag** [comment]
Oh, I just realized that I committed some codes not meant to merge.

**Comment by VaughnVernon** [comment]
@hurelhuyag Of course, but these are good examples:

https://github.com/vlingo/vlingo-lattice/blob/master/src/test/java/io/vlingo/lattice/model/sourcing/EventSourcedTest.java

First see the `setUp()` in that example and reuse as much as possible.

A simple test shows how each behavior emits and event that is then asserted as happened. For example, use your `Pet` factory method

```
public void testThatFactoryEmits() {
    final AccessSafely resultAccess = result.afterCompleting(1);
    final AccessSafely dispatcherAccess = dispatcher.afterCompleting(1);

    final Pet pet = Pet.register(...);

    // this will block until the first event is persisted in the Journal
    assertEquals(1, (int) resultAccess.readFrom("appliedCount"));
    assertEquals(1, (int) dispatcherAccess.readFrom("entriesCount"));
    Object appliedAt0 = resultAccess.readFrom("appliedAt", 0);
    assertNotNull(appliedAt0);
    assertEquals(PetRegistered.class, appliedAt0.getClass());
    BaseEntry<String> appendedAt0 = dispatcherAccess.readFrom("appendedAt", 0);
    assertNotNull(appendeAt0);
    assertEquals(PetRegistered.class.getName(), appendedAt0.typeName());
    assertFalse(resultAccess.readFrom("tested2"));
}
```

You don't need any code below this point because you have all of the interface protocols and event types already.

```
  //===========================
  // HIERARCHICAL TEST TYPES
  //===========================
```

**Review by VaughnVernon — APPROVED** [review]
@hurelhuyag  👍

**Pull request merged**
