### PR TITLE
admin-demo shows a little basic part of Hexagonal Architecture

### PR DESCRIPTION
**Pull request by anderskristian**
I have added documentation to vlingo-platform-patterns - and added feature to admin server.
In order to demo Server as an Actor / Adapter in the Hexagonal Architecture

### CODE REVIEW

**Comment by anderskristian** [comment]
I'm not committing anything to Master - except from README.md's
Here I have tried to establish some meaning with the vlingo-platform-patterns

(The other tests are failing a bit, but I have not touched these)

**Comment by VaughnVernon** [comment]
@anderskristian Thanks! Can you please indicate when you are ready to merge?

I don't see any of the issues you describe. I think some of these may be due to JDK version differences. Our team uses 1.8 as a standard. Which are you on? If above, are you able to quickly go back to 1.8 and try these?

**Comment by anderskristian** [comment]
@VaughnVernon 
IntelliJ is set to using /Users/aka/.sdkman/candidates/java/8.0.181-oracle

* The outcome from delete a **Server** varies a little from 1.2.1 to 1.2.5 - I suggest we see how 1.3.0 works  
* I will delete the branch
* I made a link in the README.md to a presentation on Hexagonal - feel free to change the link

**Comment by VaughnVernon** [comment]
@anderskristian Thanks for your efforts. I don't think that 1.3.0 will change this. Are you able to observe/determine the differences and indicate what they are?

**Comment by anderskristian** [comment]
@VaughnVernon 
I think there is **nothing burning** right now.

I just got a spike in my mind - that I have som many times worked with Spring Boot testing -- and discovered that running all test has side effects because SpringContext is **static** in various places.

In vlingo I think we could just make a new World - and everything is in a new world.
You know somewhere out there in the universe - there is another house like yours - even the same brick colour. - vlingo can prove that is correct 👍

**Comment by VaughnVernon** [comment]
The most disturbing discovery is that someone has your same name and his sisters have the same names as your sisters. Also when people mistakenly call me Vince because of Vince Vaughn and you learn that his father's name is Vernon and that he named his son Vernon. It might not be that weird except that people mistakenly call me Vince.

**Pull request merged**
