### PR TITLE
Include the vlingo-schemata-integration example in the build

### PR DESCRIPTION
**Pull request by jakzal**
While looking into schemata I noticed this example isn't included in the build. There's a risk it will run out of date if tests aren't run regurarly.

### CODE REVIEW

**Comment by jakzal** [comment]
The drawback of this is that now if you run tests locally, they'll fail if schemata wasn't started first.

**Comment by Florian-Schoenherr** [comment]
I don't really know the capabilities of Maven/modules stuff, but how about two "goals", one which runs all tests with schemata-integration and one without? Or if there's a way to specify schemata startup, we should do that.

**Comment by jakzal** [comment]
> I don't really know the capabilities of Maven/modules stuff, but how about two "goals", one which runs all tests with schemata-integration and one without? Or if there's a way to specify schemata startup, we should do that.

I think it should be possible to run a subset of modules by default and all of them on request with maven profiles. I'll attempt to do it.

> Also the integration thing only tests if it compiles after pulling, I think?

Yes, these tests are rather simplistic. I still think we should build all the modules, otherwise, we risk some of them will eventually get broken.

**Comment by jakzal** [comment]
Ok, I figured it out. 

By default, `mvn test` now won't build projects with external dependencies. However, CI will run them by using the `full` profile: `mvn test -Dfull`.

**Comment by VaughnVernon** [comment]
@jakzal Does this need more review? Will you merge when ready?

**Comment by jakzal** [comment]
We're good to go now 🚀

**Pull request merged**
